version: '2'
services:
  jwt_proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8000:8000"
    volumes:
     - .:/code
    env_file:
     - ./.env
    networks:
      - jwt-net
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
     - "8001:8001"
    volumes:
     - .:/code
    env_file:
     - ./.env
    networks:
      - jwt-net
networks:
  jwt-net:
